### ISSUE TITLE
Question: What is $A

### ISSUE THREAD

**Issue by jonaaix** [Spomky-Labs/php-aes-gcm#10]
Can you please explain what is $A (Additional Authenticated Data)? 
It is the first time I see this.

**Comment by Spomky** [comment]
[Google](https://cloud.google.com/kms/docs/additional-authenticated-data) explain the AAD concept much better than me.

The aim of AAD is to attach information to the ciphertext. The data is is not encrypted, but is bound to the ciphertext in the sense that it cannot be changed or separated.

**Comment by jonaaix** [comment]
Thank you
