### ISSUE TITLE
php-aes-gcm

### ISSUE THREAD

**Issue by andresfel27** [Spomky-Labs/php-aes-gcm#11]
buenas tardes es que el programa con los tests me arroja los siguientes errores:

Fatal error: Uncaught Error: Class 'PHPUnit_Framework_TestCase' not found in C:\Apache24\htdocs\aesgcm\tests\IEEE802Test.php:16 Stack trace: #0 {main} thrown in C:\Apache24\htdocs\aesgcm\tests\IEEE802Test.php on line 16

Fatal error: Uncaught Error: Class 'PHPUnit_Framework_TestCase' not found in C:\Apache24\htdocs\aesgcm\tests\NistTest.php:16 Stack trace: #0 {main} thrown in C:\Apache24\htdocs\aesgcm\tests\NistTest.php on line 16

Warning: include_once(C:\Apache24\htdocs\aesgcm\tests/../vendor/autoload.php): failed to open stream: No such file or directory in C:\Apache24\htdocs\aesgcm\tests\Benchmark.php on line 12

Warning: include_once(): Failed opening 'C:\Apache24\htdocs\aesgcm\tests/../vendor/autoload.php' for inclusion (include_path='.;C:\php\pear') in C:\Apache24\htdocs\aesgcm\tests\Benchmark.php on line 12

Fatal error: Uncaught Error: Class 'Assert\Assertion' not found in C:\Apache24\htdocs\aesgcm\tests\Benchmark.php:24 Stack trace: #0 C:\Apache24\htdocs\aesgcm\tests\Benchmark.php(78): runEncryptionBenchmark() #1 {main} thrown in C:\Apache24\htdocs\aesgcm\tests\Benchmark.php on line 24

si me puede ayudar seria muy amable es que lo necesito con urgencia para hacer prueba con base a este y ver que el mio me este funcionando o si sabe  una pagina donde se maneje  iv, tag, key y data, para que yo  lo pueda comprobar que si esta dando el mismo resultado que el de la pagina se lo agradezco

**Comment by Spomky** [comment]
Hi @andresfel27,

You have to install `phpunit/phpunit` (v4.x or v5.x)

**Comment by Spomky** [comment]
Closing as answered
